version: "3"

services:
  db:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "21701:21701"
    depends_on:
      - db

volumes:
  mongodb:
  mongodb_config:
