version: "3"

services:
  todo_db:
    image: mongo:4.2
    volumes:
      - todo_mongodb:/data/db
      - todo_mongodb_config:/data/configdb
  todo_web:
    build: .
    volumes:
      - .:/code
    ports:
      - "21701:21701"
    depends_on:
      - todo_db

volumes:
  todo_mongodb:
  todo_mongodb_config:
