apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web-container
  template:
    metadata:
      labels:
        app: todo-web-container
    spec:
      containers:
        - name: todo-web
          image: ashpx/todo-web
          ports:
            - containerPort: 21701
          env:
            - name: MONGODB_HOST
              value: mongodb-service

          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m

          volumeMounts:
            - name: mongodb-volume-mount
              mountPath: /var/lib/busybox

          imagePullPolicy: Never

      volumes:
        - name: mongodb-volume-mount
          persistentVolumeClaim:
            claimName: mongodb-pvc
